export type CanvasThemeId =
  | "presentation"
  | "engineering"
  | "paper"
  | "dark"
  | "sketch"
  | "mermaid"
  | "blueprint"
  | "minimal"
  | "pastel"
  | "neon";

export type CanvasGridStyle = "doubleMesh" | "mesh" | "dot" | "none";
export type CanvasConnector = "rounded" | "normal" | "smooth";
export type CanvasArrow = "block" | "classic" | "diamond";

export interface CanvasTheme {
  id: CanvasThemeId;
  label: string;
  canvas: string;
  grid: string;
  gridStrong: string;
  gridStyle: CanvasGridStyle;
  text: string;
  mutedText: string;
  edge: string;
  edgeLabel: string;
  edgeLabelBackground: string;
  edgeLabelBorder: string;
  edgeLabelRadius: number;
  edgeWidth: number;
  edgeDash?: string;
  edgeConnector: CanvasConnector;
  edgeRadius: number;
  edgeLineCap: "butt" | "round" | "square";
  arrow: CanvasArrow;
  arrowSize: number;
  groupFill: string;
  groupStroke: string;
  groupFillOpacity: number;
  groupDash?: string;
  groupRadius: number;
  defaultNode: { fill: string; stroke: string; accent: string };
  roles: Record<string, { fill: string; stroke: string; accent: string }>;
  radius: number;
  strokeWidth: number;
  fontFamily: string;
  nodeFontWeight: number;
  nodeLetterSpacing: number;
  nodeFillOpacity: number;
  nodeDash?: string;
  nodeEffect?: string;
  portFill: string;
  portRadius: number;
  portStrokeWidth: number;
  portOpacity: number;
}

export const CANVAS_THEMES: Record<CanvasThemeId, CanvasTheme> = {
  presentation: {
    id: "presentation",
    label: "SVG 卡片",
    canvas: "#f7f5ef",
    grid: "#e8e4da",
    gridStrong: "#d9d3c7",
    gridStyle: "doubleMesh",
    text: "#21302b",
    mutedText: "#625f58",
    edge: "#68736f",
    edgeLabel: "#57544e",
    edgeLabelBackground: "#fffefa",
    edgeLabelBorder: "#d8d2c7",
    edgeLabelRadius: 7,
    edgeWidth: 1.7,
    edgeConnector: "rounded",
    edgeRadius: 12,
    edgeLineCap: "round",
    arrow: "block",
    arrowSize: 9,
    groupFill: "#edf1ed",
    groupStroke: "#789187",
    groupFillOpacity: 0.58,
    groupDash: "9 5",
    groupRadius: 16,
    defaultNode: { fill: "#ffffff", stroke: "#779087", accent: "#315f50" },
    roles: {
      application: { fill: "#e8f3ee", stroke: "#599378", accent: "#28664c" },
      algorithm: { fill: "#eaf0f8", stroke: "#718cad", accent: "#395b85" },
      module: { fill: "#f3eee5", stroke: "#a58b60", accent: "#70572f" },
      service: { fill: "#f7e9e4", stroke: "#b8765f", accent: "#824934" },
      process: { fill: "#e8f3ee", stroke: "#599378", accent: "#28664c" },
      decision: { fill: "#fff4d9", stroke: "#bd8c35", accent: "#855d16" },
      data: { fill: "#e8f0fa", stroke: "#678db8", accent: "#365f8c" },
      note: { fill: "#fff8cf", stroke: "#c2a84d", accent: "#806b21" },
    },
    radius: 14,
    strokeWidth: 1.6,
    fontFamily: "Inter, Noto Sans SC, Microsoft YaHei, sans-serif",
    nodeFontWeight: 650,
    nodeLetterSpacing: 0.1,
    nodeFillOpacity: 1,
    nodeEffect: "drop-shadow(0 5px 7px rgb(54 65 60 / 16%))",
    portFill: "#ffffff",
    portRadius: 5,
    portStrokeWidth: 1.6,
    portOpacity: 1,
  },
  engineering: {
    id: "engineering",
    label: "工程制图",
    canvas: "#f5f7f8",
    grid: "#d9e1e5",
    gridStrong: "#bfcbd1",
    gridStyle: "mesh",
    text: "#17212b",
    mutedText: "#46515b",
    edge: "#394854",
    edgeLabel: "#273944",
    edgeLabelBackground: "#f5f7f8",
    edgeLabelBorder: "#8798a1",
    edgeLabelRadius: 0,
    edgeWidth: 1.35,
    edgeConnector: "normal",
    edgeRadius: 0,
    edgeLineCap: "square",
    arrow: "classic",
    arrowSize: 8,
    groupFill: "#eef2f4",
    groupStroke: "#778892",
    groupFillOpacity: 0.34,
    groupDash: "3 3",
    groupRadius: 0,
    defaultNode: { fill: "#ffffff", stroke: "#526671", accent: "#283f4b" },
    roles: {
      process: { fill: "#f7fafb", stroke: "#526671", accent: "#283f4b" },
      service: { fill: "#edf5f8", stroke: "#4d788a", accent: "#28566a" },
      decision: { fill: "#fff8e9", stroke: "#9a7937", accent: "#6e531e" },
      data: { fill: "#eef3f8", stroke: "#587893", accent: "#34566f" },
      note: { fill: "#fffceb", stroke: "#9d8c53", accent: "#665824" },
    },
    radius: 0,
    strokeWidth: 1.35,
    fontFamily: "IBM Plex Mono, Consolas, Noto Sans SC, monospace",
    nodeFontWeight: 600,
    nodeLetterSpacing: 0.35,
    nodeFillOpacity: 0.94,
    portFill: "#f5f7f8",
    portRadius: 3.5,
    portStrokeWidth: 1.3,
    portOpacity: 1,
  },
  paper: {
    id: "paper",
    label: "纸张文档",
    canvas: "#fffdf8",
    grid: "#eee9de",
    gridStrong: "#ddd4c4",
    gridStyle: "none",
    text: "#27241f",
    mutedText: "#625b51",
    edge: "#746d62",
    edgeLabel: "#5f574d",
    edgeLabelBackground: "#fffdf8",
    edgeLabelBorder: "#d8cdbc",
    edgeLabelRadius: 2,
    edgeWidth: 1.15,
    edgeConnector: "normal",
    edgeRadius: 0,
    edgeLineCap: "round",
    arrow: "classic",
    arrowSize: 9,
    groupFill: "#f8f2e7",
    groupStroke: "#b2a48e",
    groupFillOpacity: 0.48,
    groupDash: "2 5",
    groupRadius: 3,
    defaultNode: { fill: "#fffefa", stroke: "#8d8374", accent: "#5f574c" },
    roles: {
      process: { fill: "#f7f2e8", stroke: "#927d60", accent: "#655238" },
      service: { fill: "#f4eee7", stroke: "#95775e", accent: "#694d38" },
      decision: { fill: "#fff4d8", stroke: "#a87f32", accent: "#74551f" },
      data: { fill: "#edf2ef", stroke: "#6f8b7b", accent: "#476657" },
      note: { fill: "#fff6c9", stroke: "#ae9140", accent: "#725c1d" },
    },
    radius: 3,
    strokeWidth: 1.15,
    fontFamily: "Georgia, Noto Serif SC, Songti SC, serif",
    nodeFontWeight: 600,
    nodeLetterSpacing: 0.05,
    nodeFillOpacity: 0.98,
    nodeEffect: "drop-shadow(2px 3px 1px rgb(89 72 50 / 13%))",
    portFill: "#fffdf8",
    portRadius: 4.5,
    portStrokeWidth: 1.2,
    portOpacity: 0.82,
  },
  dark: {
    id: "dark",
    label: "深色演示",
    canvas: "#17201e",
    grid: "#25332f",
    gridStrong: "#30433d",
    gridStyle: "dot",
    text: "#edf5f1",
    mutedText: "#b8c7c1",
    edge: "#91aaa0",
    edgeLabel: "#d9e5e0",
    edgeLabelBackground: "#17201e",
    edgeLabelBorder: "#557067",
    edgeLabelRadius: 8,
    edgeWidth: 1.8,
    edgeConnector: "rounded",
    edgeRadius: 12,
    edgeLineCap: "round",
    arrow: "block",
    arrowSize: 9,
    groupFill: "#21302c",
    groupStroke: "#577168",
    groupFillOpacity: 0.72,
    groupDash: "8 5",
    groupRadius: 16,
    defaultNode: { fill: "#263733", stroke: "#6f9185", accent: "#a5d6c3" },
    roles: {
      process: { fill: "#214338", stroke: "#5da887", accent: "#a0dfc5" },
      service: { fill: "#3b302d", stroke: "#bd806b", accent: "#f1b29c" },
      decision: { fill: "#443b23", stroke: "#c69a45", accent: "#f0c66e" },
      data: { fill: "#26394a", stroke: "#6f9ac2", accent: "#aed4f5" },
      note: { fill: "#484022", stroke: "#bba650", accent: "#eadb86" },
    },
    radius: 13,
    strokeWidth: 1.6,
    fontFamily: "Inter, Noto Sans SC, Microsoft YaHei, sans-serif",
    nodeFontWeight: 600,
    nodeLetterSpacing: 0.15,
    nodeFillOpacity: 1,
    nodeEffect: "drop-shadow(0 0 8px rgb(112 190 160 / 18%))",
    portFill: "#17201e",
    portRadius: 5,
    portStrokeWidth: 1.5,
    portOpacity: 1,
  },
  sketch: {
    id: "sketch",
    label: "草图手绘",
    canvas: "#fffdf5",
    grid: "#eee8d8",
    gridStrong: "#ddd3bd",
    gridStyle: "none",
    text: "#282724",
    mutedText: "#625e57",
    edge: "#56534e",
    edgeLabel: "#4c4944",
    edgeLabelBackground: "#fffdf5",
    edgeLabelBorder: "#938c7d",
    edgeLabelRadius: 3,
    edgeWidth: 1.9,
    edgeDash: "7 3 2 3",
    edgeConnector: "smooth",
    edgeRadius: 0,
    edgeLineCap: "round",
    arrow: "classic",
    arrowSize: 10,
    groupFill: "#fbf7e9",
    groupStroke: "#79746b",
    groupFillOpacity: 0.44,
    groupDash: "9 4 2 4",
    groupRadius: 7,
    defaultNode: { fill: "#fffdf5", stroke: "#55524d", accent: "#35332f" },
    roles: {
      process: { fill: "#f6fbf5", stroke: "#50725d", accent: "#304f3d" },
      service: { fill: "#fff4ef", stroke: "#925f4d", accent: "#633c2e" },
      decision: { fill: "#fff7dc", stroke: "#967630", accent: "#654d19" },
      data: { fill: "#f1f6fc", stroke: "#58728e", accent: "#354e68" },
      note: { fill: "#fff3b8", stroke: "#9b8133", accent: "#67531b" },
    },
    radius: 5,
    strokeWidth: 1.9,
    fontFamily: "Comic Sans MS, Kaiti SC, STKaiti, cursive",
    nodeFontWeight: 600,
    nodeLetterSpacing: 0.35,
    nodeFillOpacity: 0.96,
    nodeDash: "8 3 2 3",
    nodeEffect: "drop-shadow(3px 3px 0 rgb(83 77 65 / 13%))",
    portFill: "#fffdf5",
    portRadius: 4,
    portStrokeWidth: 1.6,
    portOpacity: 0.75,
  },
  mermaid: {
    id: "mermaid",
    label: "Mermaid 经典",
    canvas: "#ffffff",
    grid: "#eeeeee",
    gridStrong: "#dddddd",
    gridStyle: "none",
    text: "#202020",
    mutedText: "#404040",
    edge: "#333333",
    edgeLabel: "#333333",
    edgeLabelBackground: "#fff7d6",
    edgeLabelBorder: "#d5ca93",
    edgeLabelRadius: 0,
    edgeWidth: 1.5,
    edgeConnector: "normal",
    edgeRadius: 0,
    edgeLineCap: "square",
    arrow: "block",
    arrowSize: 8,
    groupFill: "#ffffde",
    groupStroke: "#aaaa33",
    groupFillOpacity: 0.5,
    groupDash: "5 3",
    groupRadius: 0,
    defaultNode: { fill: "#ececff", stroke: "#9370db", accent: "#6f4db8" },
    roles: {
      process: { fill: "#ececff", stroke: "#9370db", accent: "#6f4db8" },
      service: { fill: "#ececff", stroke: "#9370db", accent: "#6f4db8" },
      decision: { fill: "#fff4dd", stroke: "#aa7d2e", accent: "#775418" },
      data: { fill: "#e7f4ff", stroke: "#4d83aa", accent: "#315f80" },
      note: { fill: "#ffffde", stroke: "#aaaa33", accent: "#777722" },
    },
    radius: 2,
    strokeWidth: 1.2,
    fontFamily: "trebuchet ms, verdana, arial, sans-serif",
    nodeFontWeight: 600,
    nodeLetterSpacing: 0,
    nodeFillOpacity: 1,
    portFill: "#ffffff",
    portRadius: 4,
    portStrokeWidth: 1.25,
    portOpacity: 0.9,
  },
  blueprint: {
    id: "blueprint",
    label: "蓝图技术",
    canvas: "#0b3158",
    grid: "#164875",
    gridStrong: "#2d6794",
    gridStyle: "doubleMesh",
    text: "#e9f8ff",
    mutedText: "#abd0e5",
    edge: "#86d5ef",
    edgeLabel: "#e6f8ff",
    edgeLabelBackground: "#0b3158",
    edgeLabelBorder: "#5fb5d6",
    edgeLabelRadius: 0,
    edgeWidth: 1.4,
    edgeDash: "6 4",
    edgeConnector: "normal",
    edgeRadius: 0,
    edgeLineCap: "square",
    arrow: "classic",
    arrowSize: 9,
    groupFill: "#0f3b66",
    groupStroke: "#72c5e4",
    groupFillOpacity: 0.48,
    groupDash: "7 4",
    groupRadius: 0,
    defaultNode: { fill: "#124774", stroke: "#8cdef5", accent: "#ddf8ff" },
    roles: {
      process: { fill: "#124774", stroke: "#8cdef5", accent: "#ddf8ff" },
      service: { fill: "#153f69", stroke: "#77d2ee", accent: "#d8f7ff" },
      decision: { fill: "#27496a", stroke: "#f1d27d", accent: "#fff0bd" },
      data: { fill: "#103e68", stroke: "#78cbe9", accent: "#d4f5ff" },
      note: { fill: "#254968", stroke: "#e5ce88", accent: "#fff1bd" },
    },
    radius: 0,
    strokeWidth: 1.3,
    fontFamily: "IBM Plex Mono, Consolas, Noto Sans SC, monospace",
    nodeFontWeight: 500,
    nodeLetterSpacing: 0.7,
    nodeFillOpacity: 0.72,
    portFill: "#0b3158",
    portRadius: 3.5,
    portStrokeWidth: 1.2,
    portOpacity: 1,
  },
  minimal: {
    id: "minimal",
    label: "极简黑白",
    canvas: "#ffffff",
    grid: "#f2f2f2",
    gridStrong: "#e5e5e5",
    gridStyle: "none",
    text: "#111111",
    mutedText: "#5f5f5f",
    edge: "#171717",
    edgeLabel: "#111111",
    edgeLabelBackground: "#ffffff",
    edgeLabelBorder: "#111111",
    edgeLabelRadius: 0,
    edgeWidth: 1,
    edgeConnector: "normal",
    edgeRadius: 0,
    edgeLineCap: "butt",
    arrow: "classic",
    arrowSize: 7,
    groupFill: "#ffffff",
    groupStroke: "#999999",
    groupFillOpacity: 0.05,
    groupDash: "2 4",
    groupRadius: 0,
    defaultNode: { fill: "#ffffff", stroke: "#111111", accent: "#111111" },
    roles: {
      process: { fill: "#ffffff", stroke: "#111111", accent: "#111111" },
      service: { fill: "#f5f5f5", stroke: "#111111", accent: "#111111" },
      decision: { fill: "#ffffff", stroke: "#111111", accent: "#111111" },
      data: { fill: "#fafafa", stroke: "#111111", accent: "#111111" },
      note: { fill: "#ffffff", stroke: "#555555", accent: "#111111" },
    },
    radius: 0,
    strokeWidth: 1,
    fontFamily: "Arial, Noto Sans SC, Microsoft YaHei, sans-serif",
    nodeFontWeight: 500,
    nodeLetterSpacing: 0.05,
    nodeFillOpacity: 1,
    portFill: "#ffffff",
    portRadius: 3,
    portStrokeWidth: 1,
    portOpacity: 0.72,
  },
  pastel: {
    id: "pastel",
    label: "柔和彩色",
    canvas: "#fbf8ff",
    grid: "#eee8f4",
    gridStrong: "#ded3e9",
    gridStyle: "dot",
    text: "#443b4f",
    mutedText: "#766b81",
    edge: "#86769a",
    edgeLabel: "#62556f",
    edgeLabelBackground: "#fffaff",
    edgeLabelBorder: "#dfd2e9",
    edgeLabelRadius: 10,
    edgeWidth: 2,
    edgeConnector: "smooth",
    edgeRadius: 18,
    edgeLineCap: "round",
    arrow: "diamond",
    arrowSize: 9,
    groupFill: "#f1eaf7",
    groupStroke: "#b8a6c9",
    groupFillOpacity: 0.55,
    groupDash: "10 7",
    groupRadius: 24,
    defaultNode: { fill: "#f3edfb", stroke: "#a78dbc", accent: "#765c8b" },
    roles: {
      process: { fill: "#e7f5ef", stroke: "#82ad99", accent: "#4c7864" },
      service: { fill: "#ffece8", stroke: "#cf9488", accent: "#945f55" },
      decision: { fill: "#fff2cf", stroke: "#d0a55c", accent: "#8a692f" },
      data: { fill: "#e8f1ff", stroke: "#8aa8d1", accent: "#56749b" },
      note: { fill: "#fff8c9", stroke: "#c3a653", accent: "#7f6a2e" },
    },
    radius: 22,
    strokeWidth: 1.5,
    fontFamily: "Nunito, Inter, Noto Sans SC, sans-serif",
    nodeFontWeight: 700,
    nodeLetterSpacing: 0.1,
    nodeFillOpacity: 1,
    nodeEffect: "drop-shadow(0 8px 12px rgb(109 83 127 / 13%))",
    portFill: "#fffaff",
    portRadius: 5.5,
    portStrokeWidth: 1.4,
    portOpacity: 1,
  },
  neon: {
    id: "neon",
    label: "霓虹暗色",
    canvas: "#0b0c19",
    grid: "#171a32",
    gridStrong: "#242849",
    gridStyle: "dot",
    text: "#f2efff",
    mutedText: "#aaa4ca",
    edge: "#52e5e7",
    edgeLabel: "#e8fbff",
    edgeLabelBackground: "#111329",
    edgeLabelBorder: "#3cd3d8",
    edgeLabelRadius: 9,
    edgeWidth: 2,
    edgeConnector: "smooth",
    edgeRadius: 16,
    edgeLineCap: "round",
    arrow: "diamond",
    arrowSize: 10,
    groupFill: "#11142b",
    groupStroke: "#7d63ff",
    groupFillOpacity: 0.7,
    groupDash: "4 6",
    groupRadius: 18,
    defaultNode: { fill: "#171a33", stroke: "#52e5e7", accent: "#a6ffff" },
    roles: {
      process: { fill: "#122d35", stroke: "#43e0ca", accent: "#9ffff1" },
      service: { fill: "#2d1739", stroke: "#ef69dc", accent: "#ffb1f5" },
      decision: { fill: "#332817", stroke: "#ffca57", accent: "#ffe4a0" },
      data: { fill: "#172644", stroke: "#5a9cff", accent: "#acd0ff" },
      note: { fill: "#332f18", stroke: "#e8d350", accent: "#fff4a8" },
    },
    radius: 15,
    strokeWidth: 1.7,
    fontFamily: "Inter, Noto Sans SC, Microsoft YaHei, sans-serif",
    nodeFontWeight: 650,
    nodeLetterSpacing: 0.45,
    nodeFillOpacity: 0.98,
    nodeEffect: "drop-shadow(0 0 9px rgb(72 226 221 / 30%))",
    portFill: "#0b0c19",
    portRadius: 5,
    portStrokeWidth: 1.5,
    portOpacity: 1,
  },
};

export const CANVAS_THEME_OPTIONS = Object.values(CANVAS_THEMES).map(
  ({ id, label }) => ({ id, label }),
);

export function canvasTheme(value: unknown): CanvasTheme {
  return typeof value === "string" && value in CANVAS_THEMES
    ? CANVAS_THEMES[value as CanvasThemeId]
    : CANVAS_THEMES.presentation;
}
